pygments: true
markdown: rdiscount
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

## Friends - those that have spoken at our meetups, is an organizer or helped the community
## below :-)
members:
  - name: Kalvir Sandhu
    gravatar: kalv@kalv.co.uk
    blurb: "Organizer of VanRuby meetups, co-founder of @caliper.io. Been hacking with Ruby for over 5 years"
    twitter: kalv
    url: https://caliper.io
  - name: Godfrey Chan
    gravatar: godfreykfc@gmail.com
    blurb: "A web and software developer who is passionate about building innovative, powerful and yet easy-to-use software to help users solve everyday problems."
    twitter: ChanCanCode
    url: https://caliper.io
  - name: Loki Meyburg
    gravatar: loki@medeo.ca
    blurb: "Building @Medeo by day. #VanRuby hacking by night. @Crossfit604 in the morning. Motto: simplify."
    twitter: LokiMeyburg
    url: https://medeo.ca
  - name: Charles Ellery Bergeron
    gravatar: charles@medeo.ca
    blurb: Web monkey
    twitter: CharlesEllery
    url: https://medeo.ca
